name: Testing

on:
  push:
    tags:
      - 'testing/*'


jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Get pnpm store directory
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: ${{ github.job }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ github.job }}-pnpm-store-

    - name: Initialise build environment
      run: make init

    - name: ESLint
      run: pnpm lint

    - name: Prettier
      run: pnpm exec prettier --check .

  android:

    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Get pnpm store directory
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: ${{ github.job }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml', 'cordova/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ github.job }}-pnpm-store-

    - name: Install Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9123335
        packages: 'tools platform-tools platforms;android-33 build-tools;33.0.2'

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Restore Signing Keystore
      env:
        KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE }}
      run: echo "$KEYSTORE_FILE" | base64 -d > cordova/release.jks

    - name: Restore Release Config
      env:
        BUILD_JSON: ${{ secrets.ANDROID_RELEASE_CONFIG }}
      run: echo "$BUILD_JSON" | base64 -d > cordova/build.json

    - name: Update version number
      run: make version SEMVER=${{ env.GIT_VER }}

    - name: Initialise build environment
      run: make init

    - name: Build release for Android
      run: pnpm gulp redist --platform android

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rotorflight-configurator-android-testing-${{ env.GIT_VER }}
        path: redist/*


  cleanup:

    runs-on: ubuntu-latest

    needs: [linux, macos-x86_64, macos-arm64, win64, win32, android]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Delete tag
      run: git push origin :${GITHUB_REF}

